on:
    push:
    workflow_dispatch:

# Needed for deploying the report to Github pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ssg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: actions/configure-pages@v5
      - run: go run .
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
